['BG'] = {
    ['switch_char_title'] = 'Сменете герой',
    ['switch_char_text'] = 'Натиснете E, за да смените героите',
    ['distance_check'] = 'Не можете да сменяте героите тук',
    ['staff_command_1'] = 'Добави/Премахни/Провери максимум героите на човек',
    ['action_1'] = 'действие',
    ['action_2'] = 'добави / премахни / провери',
    ['identifier_1'] = 'identifier',
    ['identifier_2'] = 'steamid / playerid',
    ['command_invalidformat'] = 'Невалиден формат - Използвай [/%s add/remove/check steamid / playerid]',
    ['player_not_online'] = 'Не е намерен играч с ID [%s]',
    ['no_permissions'] = 'Нямате разрешение да използвате тази команда',
    ['charslots_check'] = 'Този човек има %s слотове за герои',
    ['charslots_added'] = 'Добихте 1 слот за герой на - %s',
    ['charslots_recieved'] = 'Получихте 1 допълнителен слот за персонаж',
    ['charslots_remove'] = 'Премахнахте 1 слот за персонаж от - %s',
    ['charslots_removed'] = '1 слот за персонаж ви е бе отнет',
},