['CZ'] = {
    ['switch_char_title'] = 'Výběr charakteru',
    ['switch_char_text'] = 'Stiskni E pro změnění charakteru.',
    ['distance_check'] = 'Zde nelze změnit chrakter.',
    ['staff_command_1'] = 'Přidat/Odebrat/Zkontrolovat maximální počet postav hráče.',
    ['action_1'] = 'akce',
    ['action_2'] = 'Přidat / Odebrat / Zkontrolovat',
    ['identifier_1'] = 'identifier',
    ['identifier_2'] = 'steamid / playerid',
    ['command_invalidformat'] = 'Nesprávný formát - použít [/%s Přidat/Odebrat/Zkontrolovat steamid / playerid]',
    ['player_not_online'] = 'Nebyl nalezen žádný hráč [%s]',
    ['no_permissions'] = 'K použití tohoto příkazu nemáte nedostatečné oprávnění.',
    ['charslots_check'] = 'Tento hráč má %s slotov.',
    ['charslots_added'] = 'Přidali jste 1 slot - %s',
    ['charslots_recieved'] = 'Dostali jste další slot.',
    ['charslots_remove'] = 'Odobrali jste 1 slot - %s',
    ['charslots_removed'] = 'Byl vám odebrán 1 slot',
},