['DE'] = {
    ['switch_char_title'] = 'Wechsel deinen Charakter',
    ['switch_char_text'] = 'Drücke E um deinen Charakter zu wechseln',
    ['distance_check'] = 'Du kannst nicht deinen Charakter hier wechseln',
    ['staff_command_1'] = 'Füge hinzu/Setze zurück/Überprüfe die maximalen Charakter eines Spielers',
    ['action_1'] = 'action',
    ['action_2'] = 'add / remove / check',
    ['identifier_1'] = 'identifizieren',
    ['identifier_2'] = 'SteamID / SpielerID',
    ['command_invalidformat'] = 'Ungültiges Format - Benutze[/%s add/remove/check SteamID / SpielerID]',
    ['player_not_online'] = 'Es wurde kein Spieler mit der ID [%s] gefunden',
    ['no_permissions'] = 'Du bist nicht berechtigt, diesen Befehl zu verwenden',
    ['charslots_check'] = 'Dieser Spieler hat %s Charakter-Slots',
    ['charslots_added'] = 'Du hast einen Charakter-Slot t - %s',
    ['charslots_recieved'] = 'Du hast einen Extraslot erhalten',
    ['charslots_remove'] = 'Dir wurde von - %s ein Charakterslot entfernt',
    ['charslots_removed'] = 'Du hast einen Charakterslot entfernt',
},