['EN'] = {
    ['switch_char_title'] = 'Switch Character',
    ['switch_char_text'] = 'Press E to switch characters',
    ['distance_check'] = 'You can\'t switch character here',
    ['staff_command_1'] = 'Add/Remove/Check the max characters of a player',
    ['action_1'] = 'action',
    ['action_2'] = 'add / remove / check',
    ['identifier_1'] = 'identifier',
    ['identifier_2'] = 'steamid / playerid',
    ['command_invalidformat'] = 'Invalid Format - Use [/%s add/remove/check steamid / playerid]',
    ['player_not_online'] = 'No player found with the ID [%s]',
    ['no_permissions'] = 'You do not have permission to use this command',
    ['charslots_check'] = 'This user has %s character slots',
    ['charslots_added'] = 'You have added 1 character slot to - %s',
    ['charslots_recieved'] = 'You have recieved 1 extra character slot',
    ['charslots_remove'] = 'You have removed 1 character slot from - %s',
    ['charslots_removed'] = '1 character slot has been removed from you',
},