['ES'] = {
    ['switch_char_title'] = 'Cambiar Personaje',
    ['switch_char_text'] = 'Presione E para cambiar personajes',
    ['distance_check'] = 'No puedes cambiar de personaje aquí',
    ['staff_command_1'] = 'Agregar / quitar / comprobar los personajes máximos de un jugador',
    ['action_1'] = 'acción',
    ['action_2'] = 'Agregar / quitar / comprobar',
    ['identifier_1'] = 'identificador',
    ['identifier_2'] = 'ID de Steam / ID del Jugador',
    ['command_invalidformat'] = 'Formato no válido: use [/%s agregar/quitar/verificar ID de Steam / ID del Jugador]',
    ['player_not_online'] = 'No se encontró ningún jugador con el ID [%s]',
    ['no_permissions'] = 'No tienes permiso de usar este comando',
    ['charslots_check'] = 'Este usuario tiene %s espacios de personajes',
    ['charslots_added'] = 'Has agregado 1 espacio de personaje a - %s',
    ['charslots_recieved'] = 'Has recibido 1 espacio adicional de personaje',
    ['charslots_remove'] = 'Has removido 1 espacio de personaje de - %s',
    ['charslots_removed'] = 'Te han removido 1 espacio de personaje',
},