['FI'] = {
    ['switch_char_title'] = 'Vaihda hahmoa',
    ['switch_char_text'] = 'Paina E vaihtaaksesi hahmoa',
    ['distance_check'] = 'et pysty vaihtaa hahmoasi täälä',
    ['staff_command_1'] = 'lisää/poista/Tarkista pelaajan enimmäishahmot',
    ['action_1'] = 'Toiminto',
    ['action_2'] = 'Lisää / Poista / Tarkista',
    ['identifier_1'] = 'tunniste',
    ['identifier_2'] = 'steamid / pelaajaid',
    ['command_invalidformat'] = 'Väärä muoto - käytää [/%s Lisää/Poistaa/Tarkista steamid / pelaajaid]',
    ['player_not_online'] = 'tätä pelaaja ei löytynyt [%s]',
    ['no_permissions'] = 'sinulla ei ole oikeuksia tähän komentoon',
    ['charslots_check'] = 'Tällä paikalla on jo käytässä - %s',
    ['charslots_added'] = 'sinulle on lisätty 1 hahmo slotti lisää - %s',
    ['charslots_recieved'] = 'sinulla on 1 ylimääräinen hahmoi paikka',
    ['charslots_remove'] = 'sinulta poistetiin 1 hahmo paikka - %s',
    ['charslots_removed'] = '1 sinulta on poistettu yksi hahmo slotti',
},