['FR'] = {
    ['switch_char_title'] = 'Changer de personnage',
    ['switch_char_text'] = 'Appuyez sur E pour changer de personnage',
    ['distance_check'] = 'Vous ne pouvez pas changer de personnage ici',
    ['staff_command_1'] = 'Add/Remove/Check le nombre max de personnages d\'un joueur',
    ['action_1'] = 'action',
    ['action_2'] = 'add / remove / check',
    ['identifier_1'] = 'identifier',
    ['identifier_2'] = 'steamid / playerid',
    ['command_invalidformat'] = 'Format invalide - Utiliser [/%s add/remove/check steamid / playerid]',
    ['player_not_online'] = 'Aucun joueur trouvé avec l\'ID [%s]',
    ['no_permissions'] = 'Vous n\'êtes pas autorisé à utiliser cette commande',
    ['charslots_check'] = 'Cet utilisateur a %s emplacements de personnage',
    ['charslots_added'] = 'Vous avez ajouté 1 emplacement de personnage à - %s',
    ['charslots_recieved'] = 'Vous avez reçu 1 emplacement de personnage supplémentaire',
    ['charslots_remove'] = 'Vous avez supprimé 1 emplacement de personnage à - %s',
    ['charslots_removed'] = '1 emplacement de personnage vous a été retiré',
},