['NL'] = {
    ['switch_char_title'] = 'Wissel van karakter',
    ['switch_char_text'] = 'Druk E om van karakter te wisselen',
    ['distance_check'] = 'Je kunt hier niet van karakter wisselen',
    ['staff_command_1'] = 'Het maximum aantal tekens van een speler toevoegen/verwijderen/controleren',
    ['action_1'] = 'acties',
    ['action_2'] = 'toevoegen / verwijderen / controleren',
    ['identifier_1'] = 'identifier',
    ['identifier_2'] = 'steamid / spelers-id',
    ['command_invalidformat'] = 'Ongeldige Indeling - Gebruik [/%s toevoegen/verwijderen/controleren steamid / spelers-id]',
    ['player_not_online'] = 'Geen speler gevonden met de ID [%s]',
    ['no_permissions'] = 'U heeft geen toestemming om deze command te gebruiken',
    ['charslots_check'] = 'Deze gebruiker heeft %s karakterslots',
    ['charslots_added'] = 'Je hebt 1 karakterslot toegevoegd aan - %s',
    ['charslots_recieved'] = 'Je hebt 1 extra karakterslot ontvangen',
    ['charslots_remove'] = 'Je hebt 1 karakterslot verwijderd van - %s',
    ['charslots_removed'] = 'Er is 1 karakterslot van je verwijderd',
},