['SK'] = {
    ['switch_char_title'] = 'Výber charakteru',
    ['switch_char_text'] = 'Stlač E pro zmenu charakteru.',
    ['distance_check'] = 'Tu nejde zmeniť chrakter.',
    ['staff_command_1'] = 'Pridať/Odobrať/Zkontrolovať maximální počet postav hráča.',
    ['action_1'] = 'akce',
    ['action_2'] = 'Pridať / Odobrať / Zkontrolovať',
    ['identifier_1'] = 'identifier',
    ['identifier_2'] = 'steamid / playerid',
    ['command_invalidformat'] = 'Nesprávný formát - použiť [/%s Pridať/Odobrať/Zkontrolovať steamid / playerid]',
    ['player_not_online'] = 'Nebol najdený žiadny hráč [%s]',
    ['no_permissions'] = 'K použití tohto príkazu nemáte dostatočné práva.',
    ['charslots_check'] = 'Tento hráč má %s slotov.',
    ['charslots_added'] = 'Pridali ste 1 slot - %s',
    ['charslots_recieved'] = 'Dostali ste další slot.',
    ['charslots_remove'] = 'Odobrali ste 1 slot - %s',
    ['charslots_removed'] = 'Bol vám odobratý 1 slot',
},  