['SE'] = {
    ['switch_char_title'] = 'Byt Karaktär',
    ['switch_char_text'] = 'Tryck E för att byta karaktär',
    ['distance_check'] = 'Du kan inte byta karaktär här',
    ['staff_command_1'] = 'Lägg till/Ta bort/Undersök max antal karaktärer av en spelare',
    ['action_1'] = 'händelse',
    ['action_2'] = 'lägg till / ta bort / undersök',
    ['identifier_1'] = 'identifier',
    ['identifier_2'] = 'steamid / playerid',
    ['command_invalidformat'] = 'Felaktigt Format - Använd [/%s lägg till/ta bort/undersök steamid / playerid]',
    ['player_not_online'] = 'Inga spelare funna med ID [%s]',
    ['no_permissions'] = 'Du har inte tillstånd att använda detta kommandot',
    ['charslots_check'] = 'Denna spelaren har %s karaktär positioner',
    ['charslots_added'] = 'Du har lagt till 1 karaktär position till - %s',
    ['charslots_recieved'] = 'Du har mottagit 1 extra karaktär position',
    ['charslots_remove'] = 'Du har tagit bort 1 karaktär position från - %s',
    ['charslots_removed'] = '1 karaktär position har blivit borttagen',
},