['CZ'] = {
    ['settings_description'] = 'Otevřete uživatelské rozhraní nastavení Car Hud',
    ['seatbelt_description'] = 'Zapněte si bezpečnostní pás',
    ['cruise_description'] = 'Přepnout tempomat',
    ['togglecarhud_description'] = 'Přepnout uživatelské rozhraní vozu',
    ['seatbelt_on'] = 'Aktivace bezpečnostního pásu',
    ['seatbelt_off'] = 'Vypnutí bezpečnostního pásu',
    ['no_seatbelt'] = 'Toto vozidlo nemá bezpečnostní pás',
    ['cruisecontrol_on'] = 'Tempomat povolen',
    ['cruisecontrol_off'] = 'Tempomat deaktivován',
    ['no_vehicle_found'] = 'Nejste ve vozidle',
    ['remind_settings'] = 'Stisknutím %s otevřete uživatelské rozhraní nastavení a přizpůsobte si HUD svého vozu',
},