['DE'] = {
    ['settings_description'] = 'Öffne die Benutzeroberfläche der Car HUD',
    ['seatbelt_description'] = 'An-Abschnallen',
    ['cruise_description'] = 'Tempomaten (de)aktivieren',
    ['togglecarhud_description'] = 'Benutzeroberfläche der Car HUD (de)aktivieren',
    ['seatbelt_on'] = 'Sicherheitsgurt angelegt',
    ['seatbelt_off'] = 'Sicherheitsgurt geöffnet',
    ['no_seatbelt'] = 'Dieses Fahrzeug besitzt keinen Sicherheitsgurt',
    ['cruisecontrol_on'] = 'Tempomat aktiviert',
    ['cruisecontrol_off'] = 'Tempomat deaktiviert',
    ['no_vehicle_found'] = 'Du bist derzeit in keinem Fahrzeug',
    ['remind_settings'] = 'Drücke % s, um die Benutzeroberfläche der Einstellungen zu öffnen und die Car HUD anzupassen',
},