['ES'] = {
    ['settings_description'] = 'Abra la interfaz de usuario de configuración de Car Hud',
    ['seatbelt_description'] = 'Cambia tu cinturón de seguridad',
    ['cruise_description'] = 'Alternar control de crucero',
    ['togglecarhud_description'] = 'Alternar la interfaz de usuario de hud del coche',
    ['seatbelt_on'] = 'Activar cinturón de seguridad',
    ['seatbelt_off'] = 'Deshabilitar cinturón de seguridad',
    ['no_seatbelt'] = 'Este vehículo no tiene cinturón de seguridad',
    ['cruisecontrol_on'] = 'Control de crucero habilitado',
    ['cruisecontrol_off'] = 'Control de crucero desactivado',
    ['no_vehicle_found'] = 'No estás en un vehículo',
    ['remind_settings'] = 'Presione %s para abrir la interfaz de usuario de configuración y personalizar el HUD de su automóvil',
},