['FR'] = {
    ['settings_description'] = 'Ouvrez l\'interface utilisateur des paramètres de Car Hud',
    ['seatbelt_description'] = 'Basculez votre ceinture de sécurité',
    ['cruise_description'] = 'Basculer le régulateur de vitesse',
    ['togglecarhud_description'] = 'Basculer l\'interface utilisateur de la voiture',
    ['seatbelt_on'] = 'Activation de la ceinture de sécurité',
    ['seatbelt_off'] = 'Désactivation de la ceinture de sécurité',
    ['no_seatbelt'] = 'Ce véhicule n\'a pas de ceinture de sécurité',
    ['cruisecontrol_on'] = 'Régulateur de vitesse activé',
    ['cruisecontrol_off'] = 'Régulateur de vitesse désactivé',
    ['no_vehicle_found'] = 'Vous n\'êtes pas dans un véhicule',
    ['remind_settings'] = 'Appuyez sur %s pour ouvrir l\'interface utilisateur des paramètres afin de personnaliser le HUD de votre voiture',
},