['NL'] = {
    ['settings_description'] = 'Open de car hud-instellingen',
    ['seatbelt_description'] = 'Doe je gordel om',
    ['cruise_description'] = 'Schakel cruisecontrol in',
    ['togglecarhud_description'] = 'Toon car hud UI',
    ['seatbelt_on'] = 'Gordel omgedaan',
    ['seatbelt_off'] = 'Gorden uitgedaan',
    ['no_seatbelt'] = 'Dit voertuig heeft geen veiligheidsgordel',
    ['cruisecontrol_on'] = 'Cruisecontrol ingeschakeld',
    ['cruisecontrol_off'] = 'Cruisecontrol uitgeschakeld',
    ['no_vehicle_found'] = 'U zit niet in een voertuig',
    ['remind_settings'] = 'Druk %s om de instellingen-UI te openen om je auto HUD aan te passen',
},