CZ: {
    LOADING: "Načítání ...",

    FINANCE_BUTTON: "Finance",
    FINANCE_TITLE: "Financování vozidel",
    FINANCE_LEFT: "Zbývající finance:",
    FINANCE_LAST_PAYMENT: "Poslední platba:",
    FINANCE_NEXT_PAYMENT: "Další platba:",
    FINANCE_ACTION: "Zaplatit",
    FINANCE_DESCRIPTION:
      "Zadejte částku, kterou chcete dát na financování vozidel.",
    FINANCE_SUBMIT: "Odeslat",
    FINANCE_CLOSE: "Zavřít",
    FINANCE_LESS_THAN_ZERO: "Nemůžete poslat méně než 0 peněz.",
    FINANCE_INVALID_AMMOUNT: "Musíte zadat platnou částku.",

    TRANSFER_BUTTON: "Převod na osobu",
    TRANSFER_TITLE: "Převést vozidlo",
    TRANSFER_TO: "Převést na",
    TRANSFER_DESCRIPTION: "Zadejte ID osoby, které převádíte toto vozidlo.",
    TRANSFER_SUBMIT: "Odeslat",
    TRANSFER_CLOSE: "Zavřít",
    TRANSFER_INVALID_ID: "Neplatné ID hráče.",

    IMPOUND_CIV_NOTIFICATION: "Vrácení vozidla stojí 500 $.",
    IMPOUND_SELECT: "Vyberte místo k odtáhnutí",
    IMPOUND_SPAWN: "Vzít vozidlo z odtahovky",
    IMPOUND_RETURN: "Přesunout do garáže vlastníkovi",
    IMPOUND_NOTIFICATION: "This vehicle can only be returned by an officer",
    IMPOUND_TIME: "hour(s)",

    OUTSIDE_TAKEOUT: "Vyparkovat",
    OUTSIDE_RETURN: "Návrat za $",
    OUTSIDE_ENGINE: "Motor",
    OUTSIDE_FUEL: "Palivo",
    OUTSIDE_BODY: "Karoserie",
    OUTSIDE_IMPOUND_NO_VEHICLES: "Na této odtahovce nejsou vozidla",
    OUTSIDE_NO_VEHICLES: "Nemáte žádná vozidla.",
    OUTSIDE_SEARCH_PLACEHOLDER:
      "Hledejte vozidla podle štítku, jména nebo garáže",
    OUTSIDE_TOTAL_VEHICLES: "Celkem vozidel: ",

    INSIDE_UPGRADES: "Vylepšení vozidla",
    INSIDE_UPGRADES_ENGINE: "Motor",
    INSIDE_UPGRADES_BRAKES: "Brzdy",
    INSIDE_UPGRADES_SUSPENSION: "Snížení",
    INSIDE_UPGRADES_TRANSMISSION: "Převodovka",
    INSIDE_UPGRADES_TURBO: "Turbo",
    INSIDE_STATS: "Statistiky a zdraví vozidel",
    INSIDE_STATS_HANDLING: "Zpracování",
    INSIDE_STATS_ACCELERATION: "Zrychlení",
    INSIDE_STATS_BRAKES: "Brzdy",
    INSIDE_STATS_BODY: "Zdraví těla",
    INSIDE_STATS_ENGINE: "Stav motoru",
    INSIDE_STATS_FUEL: "Hladina paliva",
    INSIDE_STATS_SPEED: "Rychlost",
    INSIDE_STATS_SCORE: "Celkové skóre",

    SEARCH_BUTTON: "Vyhledávání",

    CURRENCY_SYMBOL: "$",
    KEYS_NO_KEYS: "You haven't given out any keys.",
    KEYS_REMOVE: "Remove key",
    KEYS_SEARCH: "Name or vehicle plate",
    KEYS_FOOTER: ["Total of ", " keys"],

    ACTIONBAR_TEXT: ["You have", "chance(s) left."]
  },