DE: {
    LOADING: "Laden...",

    FINANCE_BUTTON: "Finance",
    FINANCE_TITLE: "Zahle die Rate für Fahrzeug",
    FINANCE_LEFT: "Restlicher Betrag: ",
    FINANCE_LAST_PAYMENT: "Letzte Bezahlung: ",
    FINANCE_NEXT_PAYMENT: "Nächste Bezahlung bis: ",
    FINANCE_ACTION: "Zahlen",
    FINANCE_DESCRIPTION: "Gib die Summe für nächste Rate ein",
    FINANCE_SUBMIT: "Vorlegen",
    FINANCE_CLOSE: "Schließen",
    FINANCE_LESS_THAN_ZERO: "Du musst die Summe größer als 0 eingeben",
    FINANCE_INVALID_AMMOUNT: "Gültigen Betrag eingeben",

    TRANSFER_BUTTON: "Übertragen ",
    TRANSFER_TITLE: "Übertragung des Fahrzeugs",
    TRANSFER_TO: "Übetragen an",
    TRANSFER_DESCRIPTION:
      "ID von Person, an die das Fahrzeug übertragen wird, eingeben:",
    TRANSFER_SUBMIT: "Vorlegen",
    TRANSFER_CLOSE: "Schließen",
    TRANSFER_INVALID_ID: "Üngultige Spiler ID.",

    IMPOUND_CIV_NOTIFICATION: "Einlösen des Fahrzeugs kostet $500.",
    IMPOUND_SELECT: "Wähle Abschleppplatz",
    IMPOUND_SPAWN: "Spawn Fahrzeug",
    IMPOUND_RETURN: "Dem Besitzer zurückgeben",
    IMPOUND_NOTIFICATION: "This vehicle can only be returned by an officer",
    IMPOUND_TIME: "hour(s)",

    OUTSIDE_TAKEOUT: "Einlösen",
    OUTSIDE_RETURN: "Zurückgeben für $",
    OUTSIDE_ENGINE: "Motor",
    OUTSIDE_FUEL: "Moto",
    OUTSIDE_BODY: "Karosserie",
    OUTSIDE_IMPOUND_NO_VEHICLES: "Es gibt keine Fahrzeuge",
    OUTSIDE_NO_VEHICLES: "Du hast kein Fahrzeug",
    OUTSIDE_SEARCH_PLACEHOLDER:
      "Suchen Sie die Fahrzeuge nach Schild, Name oder Garage",
    OUTSIDE_TOTAL_VEHICLES: "Fahrzeuge insgesamt: ",

    INSIDE_UPGRADES: "Umrüstung des Fahrzeugs",
    INSIDE_UPGRADES_ENGINE: "Motor",
    INSIDE_UPGRADES_BRAKES: "Bremsen",
    INSIDE_UPGRADES_SUSPENSION: "Radaufhängung",
    INSIDE_UPGRADES_TRANSMISSION: "Kraftübertragung",
    INSIDE_UPGRADES_TURBO: "Turbo",
    INSIDE_STATS: "Zustand des Fahrzeugs",
    INSIDE_STATS_HANDLING: "Die Fahreigenschaften",
    INSIDE_STATS_ACCELERATION: "Beschleunigung",
    INSIDE_STATS_BRAKES: "Bremsen",
    INSIDE_STATS_BODY: "Beschleunigung",
    INSIDE_STATS_ENGINE: "Motorzustand",
    INSIDE_STATS_FUEL: "Kraftstoffstand",
    INSIDE_STATS_SPEED: "Geschwindigkeit",
    INSIDE_STATS_SCORE: "Gesamtnote",
    INSIDE_STATS_SCORE_TEXT: " SCORE",

    SEARCH_BUTTON: "Suche",

    CURRENCY_SYMBOL: "$",
    KEYS_NO_KEYS: "You haven't given out any keys.",
    KEYS_REMOVE: "Remove key",
    KEYS_SEARCH: "Name or vehicle plate",
    KEYS_FOOTER: ["Total of ", " keys"],

    ACTIONBAR_TEXT: ["You have", "chance(s) left."]