ES: {
    LOADING: "Cargando ...",

    FINANCE_BUTTON: "Finanzas",
    FINANCE_TITLE: "Financiación de Vehículo",
    FINANCE_LEFT: "Financiación restante:",
    FINANCE_LAST_PAYMENT: "Último pago:",
    FINANCE_NEXT_PAYMENT: "Próximo pago:",
    FINANCE_ACTION: "Pagar",
    FINANCE_DESCRIPTION:
      "Ingrese la cantidad de dinero que desea destinar a la financiación del vehículo",
    FINANCE_SUBMIT: "Aceptar",
    FINANCE_CLOSE: "Cerrar",
    FINANCE_LESS_THAN_ZERO: "No puedes enviar menos de 0 dólares",
    FINANCE_INVALID_AMMOUNT: "Debes ingresar una cantidad válida",

    TRANSFER_BUTTON: "Vender",
    TRANSFER_TITLE: "Transferir vehículo",
    TRANSFER_TO: "Transferir a",
    TRANSFER_DESCRIPTION:
      "Ingrese el ID de la persona a la que está transfiriendo este vehículo",
    TRANSFER_SUBMIT: "Aceptar",
    TRANSFER_CLOSE: "Cerrar",
    TRANSFER_INVALID_ID: "ID de jugador no válido",

    IMPOUND_CIV_NOTIFICATION: "Sacar un vehículo cuesta $ 500.",
    IMPOUND_SELECT: "Seleccionar un vehículo",
    IMPOUND_SPAWN: "Sacar Vehículo",
    IMPOUND_RETURN: "Devolver al propietario",
    IMPOUND_NOTIFICATION: "This vehicle can only be returned by an officer",
    IMPOUND_TIME: "hour(s)",

    OUTSIDE_TAKEOUT: "Sacar",
    OUTSIDE_RETURN: "Pagar tasas por $",
    OUTSIDE_ENGINE: "Motor",
    OUTSIDE_FUEL: "Combustible",
    OUTSIDE_BODY: "Chasis",
    OUTSIDE_IMPOUND_NO_VEHICLES: "No hay vehículos en este depósito",
    OUTSIDE_NO_VEHICLES: "No tienes ningún vehículo",
    OUTSIDE_SEARCH_PLACEHOLDER:
      "Busque los vehículos por placa, nombre o garaje",
    OUTSIDE_TOTAL_VEHICLES: "Vehículos totales: ",

    INSIDE_UPGRADES: "Mecánica del Motor",
    INSIDE_UPGRADES_ENGINE: "Motor",
    INSIDE_UPGRADES_BRAKES: "Frenos",
    INSIDE_UPGRADES_SUSPENSION: "Suspensión",
    INSIDE_UPGRADES_TRANSMISSION: "Transmisión",
    INSIDE_UPGRADES_TURBO: "Turbo",
    INSIDE_STATS: "Estadísticas & Salud",
    INSIDE_STATS_HANDLING: "Manejo",
    INSIDE_STATS_ACCELERATION: "Aceleración",
    INSIDE_STATS_BRAKES: "Frenos",
    INSIDE_STATS_BODY: "Carrocería",
    INSIDE_STATS_ENGINE: "Motor",
    INSIDE_STATS_FUEL: "Combustible",
    INSIDE_STATS_SPEED: "Velocidad",
    INSIDE_STATS_SCORE: "Puntuación",
    INSIDE_STATS_SCORE_TEXT: " SCORE",

    SEARCH_BUTTON: "Buscar",

    CURRENCY_SYMBOL: "$",
    KEYS_NO_KEYS: "You haven't given out any keys.",
    KEYS_REMOVE: "Remove key",
    KEYS_SEARCH: "Name or vehicle plate",
    KEYS_FOOTER: ["Total of ", " keys"],

    ACTIONBAR_TEXT: ["You have", "chance(s) left."]
  },