['EN'] = {
    ['settings_description'] = 'Open the car hud settings UI',
    ['seatbelt_description'] = 'Toggle your seatbelt',
    ['cruise_description'] = 'Toggle cruise control',
    ['togglecarhud_description'] = 'Toggle the car hud UI',
    ['seatbelt_on'] = 'Seatbelt enabled',
    ['seatbelt_off'] = 'Seatbelt disabled',
    ['no_seatbelt'] = 'This vehicle does not have a seatbelt',
    ['cruisecontrol_on'] = 'Cruise control enabled',
    ['cruisecontrol_off'] = 'Cruise control disabled',
    ['no_vehicle_found'] = 'You are not in a vehicle',
    ['remind_settings'] = 'Press %s to open the settings UI to customise your car HUD',
},