['ES'] = {
    ['settings_description'] = 'Abrir las opciones del HUD de vehículos',
    ['seatbelt_description'] = 'Cambiar el cinturón de seguridad',
    ['cruise_description'] = 'Cambiar control crucero',
    ['togglecarhud_description'] = 'Cambiar la interfaz del HUD',
    ['seatbelt_on'] = 'Cinturón de seguridad habilitado',
    ['seatbelt_off'] = 'Cinturón de seguridad deshabilitado',
    ['no_seatbelt'] = 'Este vehículo no tiene cinturón de seguridad',
    ['cruisecontrol_on'] = 'Control crucero habilitado',
    ['cruisecontrol_off'] = 'Control crucero deshabilitado',
    ['no_vehicle_found'] = 'No estás en un vehículo',
    ['remind_settings'] = 'Presione %s para abrir la interfaz de opciones para personalizar su HUD de vehículos',
},
