['EN'] = {
    ['saving_cached_data'] = 'Saving all cached data please wait....',
    ['cached_data_saved'] = 'Saved all cached data.',
    ['unknown'] = 'Unknown',
    ['vehicle'] = 'Vehicle',
    ['bolo'] = 'BOLO',
    ['marker'] = 'MARKER',
    ['add'] = 'Add',
    ['remove'] = 'Remove',
    ['edit'] = 'Edit',
    ['webhook_message'] = '**Player Info**\nSource: %s\nPlayer Name: %s\nCharacter Name: **%s**\nIdentifier: %s\n\n**Vehicle Info**\nPlate: **%s**\nModel: %s\nColour: %s\nMarker: %s\nNotes: %s',
    ['bot_name'] = 'Police Radar Logs',
    ['veh_owners_name'] = 'Vehicle owner lookup: %s. Copied to your clipboard',
},