Locales = { 
    ['EN'] = {
        ['saving_cached_data'] = 'Saving all cached data please wait....',
        ['cached_data_saved'] = 'Saved all cached data.',
        ['unknown'] = 'Unknown',
        ['vehicle'] = 'Vehicle',
        ['bolo'] = 'BOLO',
        ['marker'] = 'MARKER',
        ['add'] = 'Add',
        ['remove'] = 'Remove',
        ['edit'] = 'Edit',
        ['webhook_message'] = '**Player Info**\nSource: %s\nPlayer Name: %s\nCharacter Name: **%s**\nIdentifier: %s\n\n**Vehicle Info**\nPlate: **%s**\nModel: %s\nColour: %s\nReason: %s\nNotes: %s',
        ['bot_name'] = 'Police Radar Logs',
        ['veh_owners_name'] = 'Vehicle owner lookup: %s. Copied to your clipboard',
    },
    ['NL'] = {
        ['saving_cached_data'] = 'Alle data opslaan in cache, gelieve te wachten....',
        ['cached_data_saved'] = 'Alle data opgeslagen.',
        ['unknown'] = 'Onbekend',
        ['vehicle'] = 'Voertuig',
        ['bolo'] = 'FAS',
        ['marker'] = 'Nota',
        ['add'] = 'Toevoegen',
        ['remove'] = 'Verwijderen',
        ['edit'] = 'Aanpassen',
        ['webhook_message'] = '**Speler info Info**\nBron: %s\nSpeler naam: %s\nKarakter Naam: **%s**\nIdentifier: %s\n\n**Voertuig Info**\nPlaat: **%s**\nModel: %s\nKleur: %s\nReden: %s\nNotities: %s',
        ['bot_name'] = 'Politie Radar Logs',
        ['veh_owners_name'] = 'Voertuig eigenaar opzoeken: %s. Naar klembord gekopieërd',
    },
}