['DE'] = {
    ['vehicle_destroyed'] = 'Das Fahrzeug wurde zerstört',
    ['get_closer'] = 'Gehe näher an den Truck ran',
    ['menu_closed'] = 'Das Menü wurde geschlossen, da du dich zu weit vom Fahrzeug entfernt hast.',
    ['prop_already_attached'] = 'Du hast bereits eine Sache bei dir ',
    ['networking_failed'] = 'Netzwerksteuerung konnte nicht angefordert werden - bitte versuchen Sie es erneut ',
    ['registering_network'] = 'Netzwerksteuerung wird angefordert',
    ['requesting_netid'] = 'Frage Kontrolle der NetzwerkID an',
    ['not_emergancy_vehicle'] = 'Du kannst nur eine Sache vom Einsatzfahrzeug tragen',
},