['EN'] = {
    ['vehicle_destroyed'] = 'This vehicle is destroyed',
    ['get_closer'] = 'Get closer to the trunk',
    ['menu_closed'] = 'The prop menu has closed due to you moving too far away from the vehicle',
    ['prop_already_attached'] = 'You already have a prop attached to you',
    ['networking_failed'] = 'Could not request network control - please try again',
    ['registering_network'] = 'Requesting Network Control',
    ['requesting_netid'] = 'Requesting Control of Network ID',
    ['not_emergancy_vehicle'] = 'You can only grab props from an emergancy vehicle',
},