['ES'] = {
    ['vehicle_destroyed'] = 'Este vehículo está destruido',
    ['get_closer'] = 'Acercate mas al maletero',
    ['menu_closed'] = 'El menú de objetos se ha cerrado porque te has movido demasiado lejos.',
    ['prop_already_attached'] = 'Ya tienes un objeto contigo',
    ['networking_failed'] = 'No se pudo solicitar el control de la red. Vuelva a intentarlo.',
    ['registering_network'] = 'Solicitnado el control de la red',
    ['requesting_netid'] = 'Solicitando el control de la ID de red',
    ['not_emergancy_vehicle'] = 'Solo puedes coger objetos de un vehículo de emergencia',
},