['FI'] = {
    ['vehicle_destroyed'] = 'Tämä ajoneuvo on tuhottu',
    ['get_closer'] = 'mene lähemmäksi takaluukua',
    ['menu_closed'] = 'prop valikko on suljettu koska liikuit liian kauas autotsa',
    ['prop_already_attached'] = 'sinulla on jo esine',
    ['networking_failed'] = 'yritä uudelleen',
    ['registering_network'] = 'pyytää netin ohjausta',
    ['requesting_netid'] = 'Verkkotunnuksen hallinnan pyytäminen',
    ['not_emergancy_vehicle'] = 'voit ottaa vain hälyytys ajoneuvosta',
},