['FR'] = {
    ['vehicle_destroyed'] = 'Ce véhicule est détruit',
    ['get_closer'] = 'Rapprochez-vous du coffre',
    ['menu_closed'] = 'Le menu des accessoires s\'est fermé car vous vous êtes trop éloigné du véhicule',
    ['prop_already_attached'] = 'Vous avez déjà un accessoire sur vous',
    ['networking_failed'] = 'Could not request network control - please try again',
    ['registering_network'] = 'Requesting Network Control',
    ['requesting_netid'] = 'Requesting Control of Network ID',
    ['not_emergancy_vehicle'] = 'Vous ne pouvez récupérer des accessoires que dans un véhicule d\'urgence',
},