['NL'] = {
    ['vehicle_destroyed'] = 'Dit voertuig is kapot',
    ['get_closer'] = 'Kom dichter bij de kofferbak',
    ['menu_closed'] = 'Het propmenu is gesloten omdat u te ver van het voertuig bent verwijderd',
    ['prop_already_attached'] = 'Je hebt al een prop aan je vastgemaakt',
    ['networking_failed'] = 'Kan netwerkbeheer niet aanvragen - probeer het opnieuw',
    ['registering_network'] = 'Netwerkbeheer aanvragen',
    ['requesting_netid'] = 'Controle van Netwerk-ID aanvragen',
    ['not_emergancy_vehicle'] = 'Je kunt alleen props pakken uit een hulpdiensten voertuig',
},