['SK'] = {
    ['vehicle_destroyed'] = 'Toto vozidlo je zničené',
    ['get_closer'] = 'Priblížte sa ku kufru',
    ['menu_closed'] = 'Ponuka rekvizít sa zatvorila, pretože ste sa príliš vzdialili od vozidla',
    ['prop_already_attached'] = 'Už máte pripevnenú rekvizitu',
    ['networking_failed'] = 'Nepodarilo sa požiadať o kontrolu siete - skúste to znova',
    ['registering_network'] = 'Žiadosť o kontrolu siete',
    ['requesting_netid'] = 'Žiadosť o kontrolu ID siete',
    ['not_emergancy_vehicle'] = 'Rekvizity môžete chytiť iba zo záchranného vozidla',
},