['SE'] = {
    ['vehicle_destroyed'] = 'Detta fordon är förstört',
    ['get_closer'] = 'Gå närmre bakluckan',
    ['menu_closed'] = 'Prop menyn stängdes på grund utav att du är för långt ifrån fordonet',
    ['prop_already_attached'] = 'Du har redan ett prop på dig',
    ['networking_failed'] = 'Kunde inte begära nätverks kontroll - vänligen försök igen',
    ['registering_network'] = 'Begär nätverkskontroll',
    ['requesting_netid'] = 'Begär nätverkontroll av ID',
    ['not_emergancy_vehicle'] = 'Du kan endast ta props från ett utryckningsfordon',
},